from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Sequence

from pypdf import PdfWriter

here = Path(__file__).parent
EXPORT_STEM_LIMIT = 50


def load_manifest(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def build_export_name_map(abstract_dir: Path) -> dict[str, str]:
    counters: dict[str, int] = {}
    mapping: dict[str, str] = {}

    for markdown in sorted(abstract_dir.glob("*.md"), key=lambda path: path.name):
        base = markdown.stem[:EXPORT_STEM_LIMIT]
        count = counters.get(base, 0)
        counters[base] = count + 1
        export_stem = base if count == 0 else f"{base}-{count}"
        mapping[markdown.stem] = f"{export_stem}.pdf"

    return mapping


def default_pdf_order(input_folder: Path) -> list[Path]:
    return sorted(
        (
            pdf
            for pdf in input_folder.glob("*.pdf")
            if pdf.stem
            not in {"readme", "README", "all-abstracts", "all_abstracts", "fenics2026-book-of-abstracts"}
        ),
        key=lambda pdf: pdf.stem,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Merge per-abstract PDFs into a single book of abstracts.")
    parser.add_argument("-i", "--input", type=Path, default=here / "book" / "_build" / "exports")
    parser.add_argument(
        "-m",
        "--manifest",
        type=Path,
        default=here / "book" / "abstracts" / "manifest.json",
        help="Manifest generated by convert.py used to preserve abstract ordering.",
    )
    parser.add_argument(
        "-a",
        "--abstract-dir",
        type=Path,
        default=here / "book" / "abstracts",
        help="Directory containing the generated abstract markdown files.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=here / "book" / "_build" / "exports" / "fenics2026-book-of-abstracts.pdf",
    )
    args = parser.parse_args(argv)

    input_folder = args.input
    output_file = args.output.with_suffix(".pdf")
    if not input_folder.exists():
        print(f"{input_folder} does not exist")
        return 1

    readme_pdf = input_folder / "readme.pdf"
    if not readme_pdf.is_file():
        print(f"Missing required PDF: {readme_pdf}")
        print("Run `myst build --pdf` first.")
        return 1

    manifest = load_manifest(args.manifest)
    if manifest:
        export_name_map = build_export_name_map(args.abstract_dir)
        abstract_pdfs: list[Path] = []
        missing_files: list[Path] = []
        for item in manifest:
            export_name = export_name_map.get(item["slug"])
            if export_name is None:
                print(f"Could not resolve export filename for abstract: {item['slug']}")
                return 1
            pdf = input_folder / export_name
            if pdf.is_file():
                abstract_pdfs.append(pdf)
            else:
                missing_files.append(pdf)

        if missing_files:
            print("Skipping abstracts without built PDFs:")
            for path in missing_files:
                print(f" - {path.name}")
    else:
        abstract_pdfs = default_pdf_order(input_folder)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    merger = PdfWriter()
    for pdf in [readme_pdf, *abstract_pdfs]:
        merger.append(pdf)

    merger.write(output_file)
    merger.close()
    print(f"Saved to: {output_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
